name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

env:
  GAR_LOCATION: location
  GOOGLE_CLOUD_RUN_SERVICE_NAME: name_of_the_service
  IMAGE: name_of_the_image
  PROJECT_ID: project_id
  REPOSITORY: name_of_the_repo

jobs:
  build-and-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        token_format: access_token

   

    - uses: docker/login-action@v1
      name: Docker login
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Docker build
      run: |-
        docker build \
          --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest" \
          mage/.

    - name: Docker push
      run: |-
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest"

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.GOOGLE_CLOUD_RUN_SERVICE_NAME }}
        image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest
        region: ${{ env.GAR_LOCATION }}
    
    # Uncomment the step below if you are using a DBT docs service
    # - id: deploy-docs
    #   uses: google-github-actions/deploy-cloudrun@v0
    #   with:
    #     service: ${{ env.GOOGLE_CLOUD_RUN_SERVICE_NAME }}-docs
    #     image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
    #     region: ${{ env.GAR_LOCATION }}
